/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import static org.junit.Assert.assertNotNull;

public class AppTest {

    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    private WebDriver driver;

    // Настройка WebDriver
    @Before
    public void setUp() throws Exception {
// Выбор хрома как драйвера
        System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
// Конфигурация хрома. И пример запуска в headles режиме
        ChromeOptions options = new ChromeOptions();

        options.setBinary("C:/Program Files (x86)/Google/Chrome/Application/chrome.exe");
        ChromeDriver browser = new ChromeDriver(options);

        options.setHeadless(true);
// Создание инстанса браузера
        driver = new ChromeDriver(options);
    }

    // Завершение работы теста
    @After
    public void tearDown() throws Exception {
        driver.quit();
    }

    // Тест
    @Test
    public void testSuccesSearch() {
// Открытие страницы гугла
        driver.get("http://www.google.com");
// Константа для поиска
        String queryForFind = "MKDEV";
// Элемент на странице поиска, в нашем случаем строка поиска с атрибутом "name"="q"
        WebElement element = driver.findElement(By.name("q"));
// Посыл данных для поиска
        element.sendKeys(queryForFind);
// Отправка запроса
        element.submit();
// Проверка что тайтл страницы содержит искому строку
        Assert.assertTrue(
                driver.getTitle().contains(queryForFind)
        );

    }

    @Test
    public void testFailSearch() {
        driver.get("http://www.google.com");

        String queryForFind = "MKDEV";
        String failQuery = "MKDEVGoogle";

        WebElement element = driver.findElement(By.name("q"));

        element.sendKeys(queryForFind);

        element.submit();

        Assert.assertFalse(
                driver.getTitle().contains(failQuery)
        );

    }



    public static void main(String[] args) throws Exception{
       // AppTest test = new AppTest();
       // test.setUp();
       // test.testSuccesSearch();
       // test.tearDown();
    }


}
